# Exclude a variety of commonly ignored directories.
exclude = [
    ".ruff_cache",
    ".mypy_cache",
    ".pytest_cache",
    ".git",
    "__pycache__",
    "__init__.py",
    "build",
    "venv",
    "*.egg-info",
    "*.pyi",
    "src/models/nets"
]

extend-include = ["*.ipynb"]
# extend-select = ["I"] # makes ruff sort imports

# Same as Black.
line-length = 150
indent-width = 4

# Assume Python 3.11
target-version = "py311"

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
select = ["E4", "E7", "E9", "F"]
ignore = ["E401"]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
"src/models/base_model.py" = ["E722"]

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
