class_name: CommonLitModel
config:
  model:
    module: src.nn.models.nets.ukan.ukan
    class_name: StackedResidualKAN
    config:
      filters: 4
      S: 1
      L: 3
      version: spline
      spline_order: 3
      grid_size: 5
  criterion: !include "../losses/mse.yaml"
  optimizer: !include "../optimizers/adam.yaml"
