class_name: CommonLitModel
config:
  model:
    module: src.models.nets.ckan.ckan
    class_name: ConvKAN
    config:
      n_convs: 16
  criterion: !include "../losses/mse.yaml"
  optimizer: !include "../optimizers/adam.yaml"
