trainer: !include "./trainers/gpu.yaml"
model: !include "./models/srkan/model.yaml"
data:
  train_dataloaders:
  - !include "./data/ixi/train_dataloader.yaml"
  val_dataloaders:
  - !include "./data/ixi/val_dataloader.yaml"
