class_name: Trainer
config:
  model: !include "./models/ukan/srkan_4_S1_L3_mha.yaml"
  dataloader: !include "./data/dataloader.yaml"
  criterion: "MSELoss"
  optimizer: !include "./adam.yaml"
  callbacks:
  - !include "./modelcheckpoint.yaml"
  - !include "./tensorboard.yaml"
  val_dataloader: !include "./data/val_dataloader.yaml"
