trainer: !include "./trainers/gpu.yaml"
model: !include "./models/ukan/srkan_4_S1_L3_mha.yaml"
data:
  train_dataloaders:
  - !include "./data/ixi/train_dataloader.yaml"
  val_dataloaders:
  - !include "./data/ixi/val_dataloader.yaml"
