module: src.trainers
class_name: CommonLitTrainer
config:
  accelerator: gpu
  devices:
  - 0
  logger: !include "../loggers/tensorboard.yaml"
  callbacks:
  - !include "../callbacks/modelcheckpoint.yaml"
  max_epochs: 100
