module: src.models.nets
class_name: NeuralOperator
config:
  in_ch: 3
  out_ch: 1
  filters: [128, 256, 320, 512, 512]
  lifting: u-enc
  backbone: funkan
  projection: u-dec
  depth: 3
  skip: true
  r: 6
